routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SiteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main.index');
})->name('web.index');

Route::get('/daftar', function () {
    return view('layouts.daftar');
})->name('web.daftar');

Route::get('/{slug}', [SiteController::class, 'postDetails'])->name('web');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SiteController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Post;

class SiteController extends Controller
{
    public function postDetails($slug){
        $slugMap = [
            "pertanyaan-tentang-slot-online" => "faq",
            "daftar-slot-online-terbaru-2021" => "1",
            "slot-online-terpercaya" => "2",
            "10-slot-online-terbaru" => "3",
        ];

        if (array_key_exists($slug, $slugMap)) {
            $slug = $slugMap[$slug];
        }
        
        if (request()->segment(1) == 'amp') {
            if (view()->exists('amp.'.$slug)) {
                $view = 'amp.'.$slug;
            } else {
                $view = 'amp.index';
            }
        } else {
            if (view()->exists('main.'.$slug)) {
                $view = 'main.'.$slug;
            } else {
                 $view = 'main.index';
            }
        }

        return view($view);
    }
}

app/View/Components/AmpLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AmpLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('layouts.amp-main');
    }
}

app/View/Components/Layout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Layout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('layouts.main');
    }
}

resources/views/amp/1.blade.php
<x-amp-layout>
    @section('meta')
        <title>Daftar slot online terbaru 2021</title>
        <meta name="title" content="Daftar slot online terbaru 2021">
        <meta name="description"
            content="Daftar slot online terbaru 2021 yang dapat menang dengan mudah dan jackpot">
        <meta name="robots" content="index, follow">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="canonical" href="{{ route('web', 'daftar-slot-online-terbaru-2021')}}">
        <script type="application/ld+json">
            {
              "@context": "https://schema.org",
              "@type": "NewsArticle",
              "mainEntityOfPage": {
                "@type": "WebPage",
                "@id": "{{ route('web', 'daftar-slot-online-terbaru-2021')}}"
              },
              "headline": "Daftar slot online terbaru 2021",
              "image": [
                "https://images.linkcdn.cloud/V1/305/banner/305-banner-1589999223.webp"
              ],
              "datePublished": "2021-08-24T08:00:00+07:00",
              "dateModified": "2021-08-27T09:20:00+07:00",
              "author": {
                "@type": "Person",
                "name": "Jamie Anderson",
                "url": "https://hoki-slots.com/"
              },
              "publisher": {
                "@type": "Organization",
                "name": "Hokislot",
                "logo": {
                  "@type": "ImageObject",
                  "url": "https://hoki-slots.com/favicon.ico"
                }
              }
            }
        </script>
    @endsection

    <div>
        <div>
            <div class="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal" style="font-family:Georgia,serif;">

                <!--Title-->
                <div class="font-sans">
                    <h1 class="font-bold font-sans break-normal text-gray-900 pt-6 pb-2 text-3xl md:text-4xl">Daftar Slot
                        Online Terbaru 2021</h1>
                    <p class="text-sm md:text-base font-normal text-gray-600">Dibuat pada tanggal 24 Agustus 2021</p>
                </div>

                <!--Post Content-->
                @include('shared.download')

                <!--Lead Para-->
                <p class="py-6">
                    Kumpulan Judi Online Terpercaya di Tahun 2021 dan Situs Judi Slot Online Terbaru yang bisa anda temukan.
                    Masih bisa bingung mencari dan juga dalam memlih situs judi online di tahun 2021 ataupun kapanpun? Cukup mudah anda berada di situs yang paling tepat untuk menemukan website tersebut.
                    untuk para pemain yang ingin bermain judi online, Kami sang pencinta slot online game judi online berkolaborasi menciptakan game slot online yang populer pada tahun 2021.
                    Alhasil semua mesin maupun slot yang ada itu seru untuk dimainkan, banyak permainan slot online yang susah dimenangkan sehingga dompet anda terkuras dan kehabisan banyak uang. Setiap game slot online yang ada
                    di HAPPYMPO memiliki banyak pilihan jenis permainan yang asyik dan menarik, serta kreatif.Permainan slot online merupakan permainan paling populer karena sangat menuntungkan dan menantang bagi banyak orang terutama pecinta binatang, seperti singa.
                    Situs kami juga memiliki banyak aktivitas yang bisa diikuti maupun diminati. Banyak hal baru yang bisa dicoba dan dirasakan untuk dicintai banyak orang. 
                    Begitulah situs slot online terbaru 2021 yang bisa anda temukan di berbagai daerah maupun negara Indonesia.
                    Situs tersebut juga memiliki user experience yang sangat memewahkan hati serta user interface yang sangat ramah.
                </p>

                @include('shared.download')

                <h1 class="py-2 font-sans font-bold">Apa saja daftar slot online terbaru 2021</h1>
                
                <p class="py-6">
                    <ul>
                        <li><a class="text-blue-400" >Slot online Happympo</a></li>
                        <li><a class="text-blue-400" >Slot online Pragmatic</a></li>
                        <li><a class="text-blue-400" >Slot online joker123</a></li>
                        <li><a class="text-blue-400" >Poker online</a></li>
                        <li><a class="text-blue-400" >Hermit racing slot</a></li>
                        <li><a class="text-blue-400" >Pulsa slot online</a></li>
                        <li><a class="text-blue-400" >Top up slot online</a></li>
                        <li><a class="text-blue-400" >Coba slot online</a></li>
                        <li><a class="text-blue-400" >Slot online yang baik</a></li>
                        <li><a class="text-blue-400" >Pulsa slot online</a></li>
                        <li><a class="text-blue-400" >Juragan slot online</a></li>
                    </ul>
                </p>

                @include('shared.download')

                <h1 class="py-2 font-sans font-bold">Cara memainkan slot online terbaru</h1>
                
                <p class="py-6">
                     Anda dapat bermain slot online dengan memasukkan koin kedalam slot. cara mendapatkan coin yaitu
                     dengan topup pulsa maupun transfer bank, dapat menggunakan metode pembayaran gopay, ovo, shopeepay, atau transfer bank
                     dengan bank BRI, BCA, BNI, BRI syariah. setelah anda melakukan pengisian saldo maka anda dapat langsung mencoba memainkan slot online. 
                     Bukankah cara tersebut cukup simple dan mudah. Namun banyak cara bermain slot onlline terbaru 2021 lainnya yang anda dapat coba juga.
                     tentunya dengan topup saldo anda dapat mudah bermain langsung tanpa menunggu 2 x 24 jam.
                </p>

                @include('shared.download')
                
                <h1 class="py-6 font-sans font-bold">Permainan slot yang seru dan aman</h1>

                <p class="py-6">
                    Tentunya semua orang ingin bermain slot dengan aman dan mudah. Jangan tertipu dengan slot online lain, hanya di sinilah anda dapat menemukan berbagai
                    situs slot online yang seru dan juga aman. Daftarkan dan coba main maka anda dapat melihat berbagai fitur dan juga keistimewaan slot online tersebut. 
                    Tidak dapat dipungkiri kalau kita selalu memberikan hasil yang terbaik untuk masyarakat di Indonesia. Banyak daerah seperti Jakarta, Bali, Bandung juga 
                    memainkan permainan kami. Maka mulai sekarang dan dapatkan manfaat nya. Live your future with us now. berikut slogan dari situs kami. 
                    Jangan tunggu hingga kelewatan untuk mencoba hal baru yang bisa anda coba sebagai slot online untuk mendapatkan hobi baru juga.
                </p>

                @include('shared.download')
            <!--Divider-->
        </div>
        <!--/container-->

    </div>
</x-amp-layout>

resources/views/amp/faq.blade.php
<x-amp-layout>
    @section('meta')
        <title>Slot online terbaru | FAQ tentang slot online</title>
        <meta name="title" content="Slot online hoki | tempat slot terpercaya dan terbaru">
        <meta name="description" content="Berbagai pertanyaan seputar slot online, joker123, casino online yang sering di tanyakan orang.">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="canonical" href="{{ route('web','pertanyaan-tentang-slot-online')}}">

        <script type="application/ld+json">
            {
                "@context": "https://schema.org",
                "@type": "FAQPage",
                "mainEntity": [
                    {
                        "@type": "Question",
                        "name": "Apa saja slot online terbaru 2021?",
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": "<span>Terdapat banyak slot baru yang muncul, salah satu yang terbaik adalah slot <a href='{{ route('web.daftar') }}'>Happympo</a> dimana anda dapat memainkan banyak slot online terbaru dengan Berbagai jenis permainan seperti yang disediakan pada joker123, pragmatic dan berbagai service slot online terbaru lainnya. Yang pastinya apa yang disediakan oleh <a href='{{ route('web.daftar') }}'>Happympo</a> merupakan slot online terbaru yang dapat anda temukan secara online. </span>"
                        }
                    }, {
                        "@type": "Question",
                        "name": "Bagaimana cara menang slot online?",
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": "<span>Cara menang <a href='{{ route('web.daftar') }}'>Slot online</a> sebenarnya bukan sebuah rahasia. Banyak cara untuk memenangkan slot online, salah satunya adalah dengan mengontrol emosi, dan kesabatan anda. Menang dalam slot online juga merupakan faktor keberuntungan, apabila anda belum beruntung maka dapat mencoba kembali di waktu yang lain. Konsistensi adalah salah satu trik untuk memenangkan slot Online.</span>"
                        }
                    }, {
                        "@type": "Question",
                        "name": "Bagaimana cara bergabung menjadi agen casino online?",
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": "<span>Cara mendaftar cukup mudah yaitu dengan mengunjungi <a href='{{ route('web.daftar') }}'>Slot online</a> untuk mendaftar sebagai agen casino online. Agen casino online juga mempunyai banyak manfaat seperti penghasilan tambahan, beserta uang yang anda dapatkan juga lumayan banyak. Ayo gabung <a href='{{ route('web.daftar') }}'>Daftar agen casino sekarang</a>
                            </span>"
                        }
                    }
                ]
            }
        </script>
    @endsection

    <div class="font-sans">
        <h1 class="font-bold font-sans break-normal text-gray-900 pt-6 pb-2 text-3xl md:text-4xl">
            Berbagai pertanyaan mengenai slot online
        </h1>
    </div>
    @include('shared.download')
    <div class="mt-3">
        <section class="text-gray-700 pt-5">
            <div>
                <div class="text-center mb-5">
                    <p class="text-base leading-relaxed xl:w-3/4 lg:w-3/4 mx-auto">
                        Berikut merupakan daftar pertanyaan yang sering di tanyakan mengenai slot online di internet.
                        Termasuk slot yang berkaitan dengan joker123, pragmatic dan sejenisnya.
                    </p>
                </div>
                <div class="flex flex-wrap lg:w-4/5 sm:mx-auto sm:mb-2 -mx-2">
                    <div class="w-full px-4 py-2">
                        <details class="mb-4">
                            <summary class="font-semibold  bg-gray-200 rounded-md py-2 px-4">
                                Apa saja slot online terbaru 2021?
                            </summary>

                            <div class="p-5">
                                <span>
                                    Terdapat banyak slot baru yang muncul, salah satu yang terbaik adalah slot
                                    <a href="{{ route('web.daftar') }}">Happympo</a> dimana anda dapat memainkan banyak
                                    slot
                                    online terbaru dengan Berbagai
                                    jenis permainan seperti yang disediakan pada joker123, pragmatic dan berbagai
                                    service slot online terbaru lainnya. Yang pastinya apa yang disediakan oleh
                                    <a href="{{ route('web.daftar') }}">Happympo</a> merupakan slot online terbaru yang
                                    dapat
                                    anda temukan secara online.
                                </span>
                            </div>
                        </details>
                        <details class="mb-4">
                            <summary class="font-semibold bg-gray-200 rounded-md py-2 px-4">
                                Bagaimana cara menang slot online?
                            </summary>

                            <span>
                                Cara menang <a href="{{ route('web.daftar') }}">Slot online</a> sebenarnya bukan sebuah rahasia. Banyak cara untuk memenangkan slot online, salah satunya adalah
                                dengan mengontrol emosi, dan kesabatan anda. Menang dalam slot online juga merupakan faktor keberuntungan, apabila anda
                                belum beruntung maka dapat mencoba kembali di waktu yang lain. Konsistensi adalah salah satu trik untuk memenangkan slot Online.
                            </span>
                        </details>
                        <details class="mb-4">
                            <summary class="font-semibold  bg-gray-200 rounded-md py-2 px-4">
                                Bagaimana cara mendaftar sebagai agen casino?
                            </summary>

                            <span>
                                Cara mendaftar cukup mudah yaitu dengan mengunjungi <a href="{{ route('web.daftar') }}">Slot online</a>
                                untuk mendaftar sebagai agen casino online. Agen casino online juga mempunyai banyak manfaat seperti penghasilan tambahan,
                                beserta uang yang anda dapatkan juga lumayan banyak. Ayo gabung <a href="{{ route('web.daftar') }}">Daftar agen casino sekarang</a>
                            </span>
                        </details>
                    </div>
                </div>
            </div>
        </section>
    </div>
</x-layout>

resources/views/amp/index.blade.php
<x-amp-layout>
    @section('meta')
        <title>Slot online terbaru | Pusat slot online yang terpercaya dan aman</title>
        <meta name="title" content="Slot online hoki | tempat slot terpercaya dan terbaru">
        <meta name="description"
            content="Slot online hoki merupakan tempat untuk bermain berbagai jenis slot online dan menangkan banyak uang dari puluhan hingga ratusan juta rupiah.">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="canonical" href="{{ route('web.index') }}">
    @endsection


    <div>
        <div>
            <div class="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal" style="font-family:Georgia,serif;">

                <!--Title-->
                <div class="font-sans">
                    <h1 class="font-bold font-sans break-normal text-gray-900 pt-6 pb-2 text-3xl md:text-4xl">Slot
                        Online Terbaru 2021</h1>
                    <p class="text-sm md:text-base font-normal text-gray-600">Dibuat pada tanggal 17 Agustus 2021</p>
                </div>

                <!--Post Content-->
                @include('shared.download')

                <!--Lead Para-->
                <p class="py-6">
                    Slot online terbaru yang sedang populer yaitu <a class="text-blue-400"
                        href="{{ route('web.daftar') }}">Happympo</a>
                    dimana anda dapat bermain berbagai slot online yang sangat populer dan terbaru. Banyak permainan
                    slot online terbaru dan
                    terpercaya yang dapa anda coba langsung. Cara deposit juga sangat mudah dimana tersedia transfer
                    bank dan berbagai jenis
                    metode pembayaran serta withdraw. Daftar sekarang juga untuk menikmati berbagai program slot online
                    terbaru 2021 untuk mendapatkan
                    banyak hadiah dan kemenangan. Cara memenangkan slot online terbaru 2021 juga sangat mudah sehingga
                    anda dapat mendapatkan banyak
                    uang dan cashback untuk setiap permainan. Terdapat banyak jenis permainan Slot online terbaru yang
                    dapat anda pilih.
                    Coba dan daftar sekarang juga di <a class="text-blue-400" href="{{ route('web.daftar') }}">Slot online
                        terbaru 2021</a>
                </p>

                @include('shared.download')

                <h1 class="py-2 font-sans font-bold">Apa saja slot online terbaru 2021</h1>

                <p class="py-6">
                    Salah satu slot online terbaru 2021 yang bisa anda coba dan mulai yaitu <a class="text-blue-400"
                        href="{{ route('web.daftar') }}">Happympo</a>.
                    Berbagai jenis permainan seperti situs joker123, pragmatic dan sejenisnya juga terdapat disini.
                    Banyak sekali yang bisa anda coba langsung.
                    Nikmati berbagai bonus pada slot online terbaru 2021 dimana bonus tersebut dapat meningkatkan
                    keberuntungan anda dalam permainan <a class="text-blue-400" href="{{ route('web.daftar') }}">Slot
                        online terbaru 2021</a>
                    Jenis jenis slot online terbaru 2021.
                    <br>
                <ul>
                    <li><a class="text-blue-400" href="{{ route('web.daftar') }}">Happympo</a></li>
                    <li><a class="text-blue-400" href="{{ route('web.daftar') }}">Pragmatic</a></li>
                    <li><a class="text-blue-400" href="{{ route('web.daftar') }}">Joker123</a></li>
                </ul>
                </p>

                @include('shared.download')

                <h1 class="py-2 font-sans font-bold">Berbagai bonus di slot online terpercaya 2021</h1>

                <p class="py-6">
                    Terdapat banyak macam bonus pada slot online terbaru 2021 dan slot online terpercaya 2021 yang
                    berupa cashback, lucky draw, beserta banyak keberuntungan
                    lainnya yang anda bisa dapatkan setelah bergabung menjadi member <a class="text-blue-400"
                        href="{{ route('web.daftar') }}">Slot online terbaru 2021</a>.
                    Bonus tersebut juga akan bertambah dengan semakin banyak anda topup. Nikmati langsung berbagai
                    kemengangan di <a class="text-blue-400" href="{{ route('web.daftar') }}">Slot online 2021</a>.
                </p>

                @include('shared.download')

                <h1 class="py-6 font-sans font-bold">Apa itu slot online</h1>

                <p class="py-6">
                    Slot online adalah permainan slot dimana anda memutar sebuah mesin untuk mendapatkan banyak hadiah
                    yang menarik.
                    Slot online terbaru juga memiliki banyak varian seperti <a class="text-blue-400"
                        href="{{ route('web.daftar') }}">Happympo</a>, <a class="text-blue-400"
                        href="{{ route('web.daftar') }}">Joker123</a>,
                    <a class="text-blue-400" href="{{ route('web.daftar') }}">Pragmatic</a>, dan lainnya. Tentu saja
                    berbeda jenis, berbeda juga cara kerjanya.
                    tetapi semua permainan tersebuat dapat di coba langsung dengan mudah.
                </p>

                @include('shared.download')

                <h1 class="py-6 font-sans font-bold">Berbagai macam slot online terbaru 2021</h1>

                <p class="py-6">
                    Banyak slot online terbaru sejak 2021 tetapi yang paling seru dan terbaik tetap saja
                    <a class="text-blue-400" href="{{ route('web.daftar') }}">Happympo</a> karena situs tersebut sangat
                    populer dikalangan pemain slot Online.
                    Slot online tersebut juga merupakan tempat yang istimewa bagi pemain slot online terbaru karena
                    sangat khas dengan banyak hadiah.
                    Para pemain selalu semangat untuk melakukan top up maupun aktivitas lainnya
                </p>

                <table style="width:100%;border-color:#47474b;border-collapse:collapse;color:#8a8a8a;margin-left:auto;margin-right:auto;text-align:left;margin-top: 18px;margin-bottom: 18px;" border="1">
                    <tbody>
                      <tr bgcolor="#2f2f2f">
                        <td style="padding:5px"><b>Minimal Deposit</b></td>
                        <td style="padding:5px">Rp 10,000</td>
                      </tr>
                      <tr bgcolor="#2f2f2f">
                        <td style="padding:5px"><b>Minimal Withdraw</b></td>
                        <td style="padding:5px">Rp 25,000</td>
                      </tr>
                      <tr bgcolor="#2f2f2f">
                        <td style="padding:5px"><b>Waktu Deposit</b></td>
                        <td style="padding:5px">± 2 Menit</td>
                      </tr>
                      <tr bgcolor="#3e3e3e">
                        <td style="padding:5px"><b>Waktu Penarikan</b></td>
                        <td style="padding:5px">± 5 Menit</td>
                      </tr>
                      <tr bgcolor="#2f2f2f">
                        <td style="padding:5px"><b>Metode Deposit</b></td>
                        <td style="padding:5px">Bank Transfer, Crypto, Pulsa, Gopay, Dana, Ovo</td>
                      </tr>
                      <tr bgcolor="#2f2f2f">
                        <td style="padding:5px"><b>Provider Slot Terbaik</b></td>
                        <td style="padding:5px">Pragmatic Play, Slot88, PGsoft, Joker Slot</td>
                      </tr>
                    </tbody>
                  </table>

                  <ol>
                    <li>Slot Online Spadegaming</li>
                    <li>Slot Online JDB</li>
                    <li>Slot Online Playtech</li>
                    <li>Slot Online Habanero</li>
                    <li>Slot Online Pragmatic Play</li>
                    <li>Slot Online Live22</li>
                    <li>Slot88</li>
                    <li>ION Slot</li>
                    <li>Slot Online PG Soft</li>
                    <li>Slot Online Joker123</li>
                    <li>Slot Online CQ9</li>
                    <li>Slot Online YGGDRASIL</li>
                    <li>Slot Online Microgaming</li>
                    <li>Slot Online Play'n Go</li>
                    <li>Slot Online One Touch Gaming</li>
                    <li>RTG Slot</li>
                    <li>Slot Online Flow Gaming</li>
                    <li>Slot Online Iconic Gaming</li>
                </ol>
                <!--Divider-->
            </div>
            <!--/container-->

        </div>
</x-amp-layout>

resources/views/shared/amp-carousel.blade.php
<div class="carousel relative shadow-2xl bg-white">
    <a href="{{ route('web.daftar') }}">
        <amp-img class="d-block w-100" width="1698" height="300" layout="responsive"
            src="https://images.linkcdn.cloud/V1/305/banner/305-banner-286567468.webp"
            alt="Slot online terbaru dan terpercaya">
    </a>
    <a href="{{ route('web.daftar') }}">
        <amp-img class="d-block w-100" width="1698" height="300" layout="responsive"
            src="https://images.linkcdn.cloud/V1/305/banner/305-banner-2006719481.webp"
            alt="10 slot online terbaru">
    </a>
    <a href="{{ route('web.daftar') }}">
        <amp-img class="d-block w-100" width="1698" height="300" layout="responsive"
            src="https://images.linkcdn.cloud/V1/305/banner/305-banner-1668875076.webp"
            alt="Slot online terbaru">
    </a>
    <a href="{{ route('web.daftar') }}">
        <amp-img class="d-block w-100" width="1698" height="300" layout="responsive"
            src="https://images.linkcdn.cloud/V1/305/banner/305-banner-1152994417.webp"
            alt="Slot online terpercaya 2021">
    </a>
    <a href="{{ route('web.daftar') }}">
        <amp-img class="d-block w-100" width="1698" height="300" layout="responsive"
            src="https://images.linkcdn.cloud/V1/305/banner/305-banner-1763143013.webp"
            alt="Main slot online">
    </a>
    <a href="{{ route('web.daftar') }}">
        <amp-img class="d-block w-100" width="1698" height="300" layout="responsive"
            src="https://images.linkcdn.cloud/V1/305/banner/305-banner-1077412630.webp"
            alt="Coba slot online terpercaya">
    </a>
    <a href="{{ route('web.daftar') }}">
        <amp-img class="d-block w-100" width="1698" height="300" layout="responsive"
            src="https://images.linkcdn.cloud/V1/305/banner/305-banner-1589999223.webp"
            alt="Slot online terbaru 2021">
    </a>
</div>

resources/views/shared/amp-nav.blade.php
<nav id="header" class="fixed w-full z-10 top-0 bg-white">

    <div id="progress" class="h-1 z-20 top-0"
        style="background:linear-gradient(to right, #4dc0b5 var(--scroll), transparent 0);"></div>

    <div class="w-full md:max-w-4xl mx-auto flex flex-wrap items-center justify-between mt-0 py-3">

        <div class="pl-4">
            <a class="text-gray-900 no-underline hover:no-underline font-bold text-xl" href="/">
                Slot Hoki Jackpot
            </a>
        </div>

        <div class="block lg:hidden pr-4">
            <button id="nav-toggle"
                class="flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-gray-900 hover:border-green-500 appearance-none focus:outline-none">
                <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <title>Menu</title>
                    <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
                </svg>
            </button>
        </div>

        <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block mt-2 lg:mt-0 bg-gray-100 md:bg-transparent z-20"
            id="nav-content">
            <ul class="list-reset lg:flex justify-end flex-1 items-center">
                <li class="mr-3">
                    <a class="self-center uppercase w-60 text-center bg-purple-600 shadow-2xl py-1 px-2 rounded-full text-white" href="{{ route('web.daftar') }}">Daftar slot online</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/shared/download.blade.php
<div class="p-2 m-2 text-center">
    <div
        class="inline-flex items-center bg-purple-600 leading-none rounded-full p-2 shadow text-teal text-sm">
        <a href="{{ route('web.daftar') }}">
            <span class="inline-flex bg-purple-600 text-white rounded-full h-6 px-3 justify-center items-center">DAFTAR SLOT ONLINE</span>
        </a>
    </div>
</div>